server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username:
    url:
    password:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate